name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Test packed consumer
        run: pnpm run test:packed-consumer

      - name: Test coverage
        run: pnpm run test:coverage
        env:
          CI: true

      - name: Lint
        run: pnpm run lint
